### ISSUE TITLE
Extract CSV, with field delimiter consistent with the schema used

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1009]
Please replace this line with full information about your idea or problem. If it's a bug share as much as possible to reproduce it.

I have this input CSV file:

```
fieldNameA;fieldNameB
0123;c
```

If I run `extract` the field delimiter is changed from `;` to `,`:

```
fieldNameA,fieldNameB
123,c
```

I think that the default way should be to have the output field separator as the one of the input.

Moreover if I have this schema, in which I set `delimiter: ;`

```yaml
path: input.csv
name: input
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: utf-8
dialect:
  delimiter: ;
schema:
  fields:
    - type: integer
      name: fieldNameA
    - type: string
      name: fieldNameB
```

and then run `frictionless extract input.yml --csv`, I have again `,` as field separator and it's inconsistent with the schema I have.

```
fieldNameA,fieldNameB
123,c
```

I think that if I use a schema, I should have a consistent output also for delimiter setting.
This is related to this [discussion](https://github.com/frictionlessdata/project/discussions/715#discussioncomment-2412867=).

Thank you

**Comment by aborruso** [comment]
@roll will there be any news on this point with the 5 release?

Thank you

**Comment by roll** [comment]
@aborruso 
The v5 changes have not affected it so I'll prioritize this now

**Comment by aborruso** [comment]
> The v5 changes have not affected it so I'll prioritize this now

Hi @roll
using the below files and frictionless 5, if I run `frictionless extract input.yaml --csv`, I have in output 

```
frictionless extract input.yaml --csv
fieldNameA,fieldNameB
123,c
```

This is  inconsistent with the schema I have, in which my delimiter is `;`.
If this is a choice, that the output is always with a comma, I close the issue.

Thank you



```
fieldNameA;fieldNameB
123;c
```

```
path: input.csv
name: input
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: utf-8
dialect:
  delimiter: ;
schema:
  fields:
    - type: integer
      name: fieldNameA
    - type: string
      name: fieldNameB
```
