### ISSUE TITLE
Is there a CLI way to change the order of fields properties in describe output?

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1146]
Is there a way in example to have name before all?

The default output is

```yml
- type: boolean
  name: UE
- type: boolean
  name: test
```

I think that to have name as the first properties is more human readable and I would like to have

```yml
- name: UE
  type: boolean
- name: test
  type: boolean
```

Thank you
