### ISSUE TITLE
Data extracted from package refer to resources using `path` and not `name`

### ISSUE THREAD

**Issue by vlcinsky** [frictionlessdata/frictionless-py#1160]
# Overview

My package contains two resources, named "countries" and "classes" which are read from "COUNTRIES.csv" and "CLASSES.csv"

When extracting the data, I found, that individual resources on output are named using path to CSV files and not using given resource name.

```yaml
CLASSES.csv:
- CLASS: A
- CLASS: L
- CLASS: P
COUNTRIES.csv:
- CCD: 2
  CID: 11
  CNAME: Czech Republic
  ECC: E2
```
# `package.yaml` package descriptor

The `package.yaml` file define explicit names for resources:
```yaml
resources:
  - path: COUNTRIES.csv
    name: countries
    profile: tabular-data-resource
    scheme: file
    format: csv
    hashing: md5
    encoding: utf-8-sig
    dialect:
      delimiter: ;
    schema:
      fields:
        - type: integer
          name: CID
        - type: string
          name: ECC
        - type: integer
          name: CCD
        - type: string
          name: CNAME
  - path: CLASSES.csv
    name: classes
    profile: tabular-data-resource
    scheme: file
    format: csv
    hashing: md5
    encoding: utf-8-sig
    schema:
      fields:
        - type: string
          name: CLASS
profile: tabular-data-package
```
# Discussion about properly naming resources in tabular package extract output
The [Data Resource specification](https://specs.frictionlessdata.io/data-resource/#name) defines `name` property as required while `path` might be replaced by `data` property.

At the same time, value of `path` property can be quite long (using url etc.) while `name` is there to be short representation of the resource identity.

For these reasons it seems to me better to identify resources in extract output using resource name and not using `path`.
