### ISSUE TITLE
CLI frictionless `summary` ignores `required` property of fields

### ISSUE THREAD

**Issue by vlcinsky** [frictionlessdata/frictionless-py#1161]
# Overview

`frictionless summary countries.resource.yaml` command ignores real value field property `required`

# Input data

File `COUNTRIES.csv`:
```csv
CID;ECC;CCD;CNAME
11;E2;2;Czech Republic
```

File `countries.resource.yaml`:
```yaml
# --------
# metadata: COUNTRIES.csv
# --------

path: COUNTRIES.csv
name: countries
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: utf-8-sig
dialect:
  delimiter: ;
schema:
  fields:
    - type: integer
      name: CID
      required: true
    - type: string
      name: ECC
      required: false
    - type: integer
      name: CCD
    - type: string
      name: CNAME
```
# Summary output
```shell
$ frictionless summary countries.resource.yaml

# Describe 

+--------+---------+------------+
| name   | type    | required   |
+========+=========+============+
| CID    | integer |            |
+--------+---------+------------+
| ECC    | string  |            |
+--------+---------+------------+
| CCD    | integer |            |
+--------+---------+------------+
| CNAME  | string  |            |
+--------+---------+------------+

# Extract 

+-----+------+-----+------------------+
| CID | ECC  | CCD | CNAME            |
+=====+======+=====+==================+
|  11 | 'E2' |   2 | 'Czech Republic' |
+-----+------+-----+------------------+


# Validate 

# -----
# valid: COUNTRIES.csv 
# -----

## Summary 

+------------------------+-------------------+
| Description            | Size/Name/Count   |
+========================+===================+
| File name              | COUNTRIES.csv     |
+------------------------+-------------------+
| File size (bytes)      | 46                |
+------------------------+-------------------+
| Total Time Taken (sec) | 0.008             |
+------------------------+-------------------+
```
As can be seen, `required` columns is empty, regardless of the fact:
- field `CID` is explicitly required
- field `ECC` is explicitly not required
- fields `CCD` and `CNAME` shall be by definition (as default value) required

**Comment by roll** [comment]
Hi @vlcinsky, according the the specs - https://specs.frictionlessdata.io/table-schema/ - it needs to be set as:

```
# --------
# metadata: COUNTRIES.csv
# --------

path: COUNTRIES.csv
name: countries
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: utf-8-sig
dialect:
  delimiter: ;
schema:
  fields:
    - type: integer
      name: CID
      constraints:
        required: true
    - type: string
      name: ECC
      constraints:
        required: false
    - type: integer
      name: CCD
    - type: string
      name: CNAME
```
