### ISSUE TITLE
Implement `steps.table_to_schema`

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1168]
# Overview

To achieve the goal from this issue - https://github.com/frictionlessdata/frictionless-py/issues/922 - we can use transform. Initially we needed it for the Livemark Table plugin so it's fine to use transform here.

> resource.yaml (v5)

```yaml
path: table.csv
pipeline:
  steps:
    - code: table-to-schema
      schema: <your-schema>
```

On `resource.transform()` it will reshape the data to match the schema.

PS.
We're going to use transform for this to keep our `describe` functionality pure as the initial idea of a defining schema (from #922) would break this concept
