### ISSUE TITLE
CKAN plugin import violates name pattern validation

### ISSUE THREAD

**Issue by n0rdlicht** [frictionlessdata/frictionless-py#1207]
# Overview

When using `format: ckan` the name of the resource/package is directly copied from the name the portal uses. This leads to violations in name validation.

Example:
```yaml
# src/example.pipeline.yaml

tasks:
  - type: resource
    source:
      name: data
      path: https://data.stadt-zuerich.ch
      format: ckan
      dialect:
        dataset: bev_monat_zuz_quartier_geschl_ag_herkunft_od3530
        resource: BEV353OD3530.csv
    steps:
    - code: table-write
      path: data-cache/stadt-zuerich-zuzug.csv

```

```bash
$ frictionless transform src/example.pipeline.yaml
[task-error] The task has an error: [resource-error] The data resource has an error: "'BEV353OD3530.csv' does not match '^([-a-z0-9._/])+$'" at "name" in metadata and at "properties/name/pattern" in profile
```

Please replace this line with full information about your idea or problem. If it's a bug share as much as possible to reproduce it
