### ISSUE TITLE
Write in the documentation what's the CLI extract default encoding

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1231]
Hi,
if I understand correctly, it's UTF-8. If it is confirmed I would write it in the documentation.

Thank you

**Comment by shashigharti** [comment]
Hi @aborruso 

Thank you. While reading files, detect_encoding function infers the encoding and if encoding is not detected or if it detected with less confidence, then the default is set to UTF-8.

[detect_encoding](https://github.com/frictionlessdata/framework/blob/main/frictionless/detector/detector.py#L192)

**Comment by aborruso** [comment]
Hi @shashigharti and thank you.

> Thank you. While reading files, detect_encoding function infers the encoding and if encoding is not detected or if it detected with less confidence, then the default is set to UTF-8.

I probably haven't explained myself.

I have this [csv file](https://github.com/frictionlessdata/framework/files/9452983/input-iso8859-1.zip) `iso8859-1` encoded.

If I describe it, I have back the right encoding:

```
# --------
# metadata: input-iso8859-1.csv
# --------

path: input-iso8859-1.csv
name: input-iso8859-1
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: iso8859-1
schema:
  fields:
    - type: string
      name: FieldA
    - type: integer
      name: FieldB
```

If I extract it, simply run

```
frictionless extract --csv input-iso8859-1.csv >out.csv
```

the output file does not keep the original encoding, but it's a UTF-8 CSV file. 
If you confirm this to me, I would add a note in the extract documentation. Something like "the extract output encoding is UTF-8".

Thank you
