### ISSUE TITLE
Cast int cell to string in excel file

### ISSUE THREAD

**Issue by l-vincent-l** [frictionlessdata/frictionless-py#1251]
Let's say I want to parse the attached file.
It has in the A column `string` or `int`, but I want every cells of that column to be `string`.

I tried with this package.yaml

```yaml
resources:
  - name: example
    type: table
    path: example.xlsx
    scheme: file
    format: xlsx
    encoding: utf-8
    mediatype: application/vnd.ms-excel
    schema:
      fields:
        - name: A
          type: string
        - name: B
          type: string
    pipeline:
      steps:
        - type: table-normalize
        - type: field-merge
          fromNames:
            - A
            - B
          name: AB
```

and runned this python script

```python
from frictionless import Package

p = Package.from_descriptor('package-issue.yaml')

p.extract()

for r in p.resources:
    r.transform()
    print(r.to_view())
```

I have this error when I try to tranform it with `field-merge`
```
frictionless.exception.FrictionlessException: [step-error] Step is not valid: "field_merge" raises "sequence item 0: expected str instance, NoneType found" 
```

Is there a way to cast all ints in `string` ?

[example.xlsx](https://github.com/frictionlessdata/framework/files/9526532/example.xlsx)

**Comment by roll** [comment]
@l-vincent-l 
Thanks for reporting! We will investigate both issues

**Comment by shashigharti** [comment]
Hi @l-vincent-l, 

Thanks!. Can you please try the following methods:

1. First method: Set the format of the column in excel file to string and then read the resource. And use preserve_formatting=True as follows:
```
descriptor = {
  "resources": [
    {
      "name": "example",
      "type": "table",
      "path": "example.xlsx",
      "scheme": "file",
      "format": "xlsx",
      "encoding": "utf-8",
      "mediatype": "application/vnd.ms-excel",
      "schema": {
        "fields": [
          {
            "name": "A",
            "type": "string"
          },
          {
            "name": "B",
            "type": "string"
          },
          {
            "name": "C",
            "type": "string"
          },
          {
            "name": "D",
            "type": "any"
          },
          {
            "name": "E",
            "type": "integer"
          }
        ]
      }
    }
  ]
}
from frictionless import Package, Resource, formats, Pipeline, steps
control = formats.ExcelControl(preserve_formatting=True)
p = Package.from_descriptor(descriptor)
pipeline = Pipeline(
  steps=[
            steps.field_merge(name="F", from_names=["C", "B"]),
        ],
)
for resource in p.resources:
    resource = Resource(resource.to_descriptor(), control = control)
    print(resource.to_view())
    transform = resource.transform(pipeline)
    print(transform.to_view())
```
```
+-------+-----+-----+-----+---+
| A     | B   | C   | D   | E |
+=======+=====+=====+=====+===+
| '001' | 'b' | '1' | 'a' | 1 |
+-------+-----+-----+-----+---+
| '002' | 'c' | '1' |   1 | 1 |
+-------+-----+-----+-----+---+

+-------+-----+---+-------+
| A     | D   | E | F     |
+=======+=====+===+=======+
| '001' | 'a' | 1 | 'b-1' |
+-------+-----+---+-------+
| '002' |   1 | 1 | 'c-1' |
+-------+-----+---+-------+
```


2. Second method: Use CSV format. 

```
descriptor = {
  "resources": [
    {
      "name": "example",
      "type": "table",
      "path": "example.csv",
      "scheme": "file",
      "schema": {
        "fields": [
          {
            "name": "A",
            "type": "string"
          },
          {
            "name": "B",
            "type": "string"
          },
          {
            "name": "C",
            "type": "string"
          },
          {
            "name": "D",
            "type": "any"
          },
          {
            "name": "E",
            "type": "integer"
          }
        ]
      }
    }
  ]
}
from frictionless import Package, Resource, formats, Pipeline, steps
package = Package.from_descriptor(descriptor)
pipeline = Pipeline(
  steps=[
            steps.field_merge(name="F", from_names=["C", "B"]),
        ],
)
for resource in package.resources:
    print(resource.to_view())
    transform = resource.transform(pipeline)
    print(transform.to_view())
```

```
+-------+-----+-----+-----+---+
| A     | B   | C   | D   | E |
+=======+=====+=====+=====+===+
| '001' | 'b' | '1' | 'a' | 1 |
+-------+-----+-----+-----+---+
| '002' | 'c' | '1' | '1' | 1 |
+-------+-----+-----+-----+---+

+-------+-----+---+-------+
| A     | D   | E | F     |
+=======+=====+===+=======+
| '001' | 'a' | 1 | 'b-1' |
+-------+-----+---+-------+
| '002' | '1' | 1 | 'c-1' |
+-------+-----+---+-------+
```
Files used
[example.csv](https://github.com/frictionlessdata/framework/files/9615528/example.csv)
[example.xlsx](https://github.com/frictionlessdata/framework/files/9615529/example.xlsx)

**Comment by yohanboniface** [comment]
Jumping in (I work with @l-vincent-l ) to add a bit of context to the initial question

We use Frictionless/Table Schema in a workflow where we do not control the data/dataset production. Instead, we actually use Frictionless/Table Schema to add a postprocess schema so to "normalize" the data before it get imported.

Does that usage makes sense to you ?

Thanks!

**Comment by shashigharti** [comment]
Thanks @yohanboniface. I did not understand fully. Could you please explain in detail your usecase with data ? Question that I have is:

-> Is data generated/produced of same type or different in terms of files, format?

**Comment by yohanboniface** [comment]
@shashigharti we have an ETL where we ingest data that we do not produce. The dataset file and format is known, but we cannot change it.

In other words, we want to be able to import any dataset from anywhere on the Internet, "just" by defining a "schema file" on our side that would give to our ETL the rules needed to "normalize" the data before importing it in our database. By normalizing, I mean making sure for example that an int column only contains int, or mapping "pseudo booleans" to a real boolean column, or making sure that some administrative codes are valid, etc.

The ETL output is a normalized table in a postgresql database (each resource ends in a separate table).

To give a bit more details: we currently have our own code base, very similar to Frictionless, and we are evaluating the opportunity to use Frictionless, instead of reinventing the wheel.

To have an example of how we describe our ETL steps currently: https://datahub.incubateur.tech/infrastructure/insitu/-/blob/main/insitu/datasets/numerique.yml

Hope this helps! :)

**Comment by shashigharti** [comment]
Thanks! @yohanboniface, now it is clear.

I will discuss this with @roll  and reply here.

**Comment by roll** [comment]
We're releasing `frictionless@5.0.0b11` that now supports `formats.ExcelControl.stringified`:

```
resources:
  - name: example
    type: table
    path: example.xlsx
    scheme: file
    format: xlsx
    encoding: utf-8
    mediatype: application/vnd.ms-excel
    dialect:
      excel:
        stringified: true
    schema:
      fields:
        - name: A
          type: string
        - name: B
          type: string
    pipeline:
      steps:
        - type: table-normalize
        - type: field-merge
          fromNames:
            - A
            - B
          name: AB
```
