### ISSUE TITLE
Unable to do a table-write of a table with foreignkeys to a postgres database

### ISSUE THREAD

**Issue by l-vincent-l** [frictionlessdata/frictionless-py#1252]
If I have this `package.yaml` file
```yaml
name: petites_villes_de_demain
resources:
  - name: commune
    dialect:
      sql:
        table: commune
    format: sql
    mediatype: application/sql
    path: postgresql://user:pwd@localhost/mydb
    type: table
    schema:
      fields:
      - name: insee_com
        type: string
        constraints:
          required: true
      primaryKey:
      - insee_com
  - name: diffusion-zonages-zrr-cog2021
    type: table
    path: https://www.data.gouv.fr/fr/datasets/r/4160134c-017c-42c7-b838-6048ad56e5f2
    scheme: https
    format: xls
    encoding: utf-8
    mediatype: application/vnd.ms-excel
    dialect:
      headerRows:
        - 6
    schema:
      fields:
        - name: CODGEO
          type: string
        - name: LIBGEO
          type: string
        - name: ZRR_SIMP
          type: string
        - name: ZONAGE_ZRR
          type: string
      foreignKeys:
        - fields: CODGEO
          reference:
            resource: commune
            fields:
              - insee_com

    pipeline:
      steps:
      - type: table-write
        path: postgresql://user:pwd@localhost/mydb
        dialect:
              sql:
                table: zrr
```

*TLDR* This file describes a package with 2 resources : 
 * one is the list of towns if France, it's stored in a postgresql table
 * the other one describes data linked to towns, and it has a pipeline that writes this table to the postgresql datababase.
 
 Currently this doesn't work because when we called the `table-write` on the resource we don't have knowledge of the original package anymore.
 To do the transformation there is a creation of a new package [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/formats/sql/storage.py#L181), so when we prepare the lookups we don't find the resource we are looking for, and it raises an exception [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/resource/resource.py#L720)
