### ISSUE TITLE
Not able to use validate in frictionless 5

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1281]
Hi,
using frictionless 4 if I run

```
frictionless validate ./info.yml --path input.csv
```

I have right validation output. 

If I use the same command using the 5 version, it validates not the csv file, it validates the yml one.

```
# -----
# valid: ./info.yml (non-tabular)
# -----

## Summary

+--------------+---------------+
| Name         | Value         |
+==============+===============+
| File Place   | ./info.yml    |
+--------------+---------------+
| File Size    | 1.4 kB        |
+--------------+---------------+
| Total Time   | 0.414 Seconds |
+--------------+---------------+
| Rows Checked |               |
+--------------+---------------+
```

Am I doing something wrong? How to validate a file using an yml descriptor file?

Thank you

## Files

```
id,Comune,temperatura_corporea,area,email,data
1,Cefalu',36.26,,info@email.it,12/27/2022
7,Santa Flavia,-28,,posta@emailit,12/2/2022
```

```yml
path: input_01_fd.csv
encoding: utf-8
name: input
profile: tabular-data-resource
format: csv
hashing: md5
dialect:
  delimiter: ","
schema:
  missingValues: ["NaN","-",""]
  fields:
    - name: id
      title: "Identificativo"
      description: "Codice univoco identificativo"
      type: integer
      constraints:
        required: true
        unique: true
      example: 1
    - name: Comune
      title: "Comune"
      description: "Nome del Comune in cui si è svolta la misurazione"
      type: string
      example: "Trieste"
    - name: temperatura_corporea
      title: "Temperatura corporea"
      description: "Valore in grado Celsius della temperatura corporea"
      type: number
      constraints:
        minimum: 34
      example: 36.12
    - name: area
      title: "Area"
      description: "Area geografica in una delle seguenti categorie: Nord, Centro, Sud"
      type: any
      constraints:
        enum:
          - Nord
          - Centro
          - Sud
      example: "Nord"
    - name: email
      title: "Indirizzo email"
      description: "Indirizzo email del soggetto"
      type: string
      format: email
      example: "esempio@tin.it"
    - name: data
      title: "Data misurazione"
      description: "Data in cui è stata effettuata la misurazione, nel formato YYYY-MM-DD"
      type: date
      format: default
      example: "2022-12-31"
```
