### ISSUE TITLE
frictionless extract --valid: it does not work properly with date fields, using "default" format

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1282]
Hi,
if I run

```
frictionless extract --csv --valid ./info.yml --path input.csv
```

I have

```
5,Santa Flavia,37.2,,utente@email.it,default
```

Please note the last field: it does not contain its cell value, but in some way the field type.
If I remove `format: default` from the yml file, it works.

Is it wrong to use `format: default`? Is it the standard and inserting it is an error?

I'm using 4.40.8.

Thank you

## Files

```
id,Comune,temperatura_corporea,area,email,data
1,Cefalu',36.26,,info@email.it,12/27/2022
,Santa Flavia,-28,,posta@emailit,12/2/2022
5,Santa Flavia,37.2,,utente@email.it,2022-12-02
5,Santa Flavia,36.2,,persona@email.it,2021-08-23
```

```yml
path: input_01_fd.csv
encoding: utf-8
name: input
profile: tabular-data-resource
format: csv
hashing: md5
dialect:
  delimiter: ","
schema:
  missingValues: ["NaN","-",""]
  fields:
    - name: id
      title: "Identificativo"
      description: "Codice univoco identificativo"
      type: integer
      constraints:
        required: true
        unique: true
      example: 1
    - name: Comune
      title: "Comune"
      description: "Nome del Comune in cui si è svolta la misurazione"
      type: string
      example: "Trieste"
    - name: temperatura_corporea
      title: "Temperatura corporea"
      description: "Valore in grado Celsius della temperatura corporea"
      type: number
      constraints:
        minimum: 34
      example: 36.12
    - name: area
      title: "Area"
      description: "Area geografica in una delle seguenti categorie: Nord, Centro, Sud"
      type: any
      constraints:
        enum:
          - Nord
          - Centro
          - Sud
      example: "Nord"
    - name: email
      title: "Indirizzo email"
      description: "Indirizzo email del soggetto"
      type: string
      format: email
      example: "esempio@tin.it"
    - name: data
      title: "Data misurazione"
      description: "Data in cui è stata effettuata la misurazione, nel formato YYYY-MM-DD"
      type: date
      format: default
      example: "2022-12-31"

```

**Comment by aborruso** [comment]
@roll I know this is a 0.4 point, but I must use 0.4, because I have [some problems](https://github.com/frictionlessdata/framework/issues/1281) with 0.5 and validate.

**Comment by shashigharti** [comment]
Thanks @aborruso we will investigate!.

**Comment by shashigharti** [comment]
Hi @aborruso,

It is a  bug in v.40.8 but fixed in v5 and workaround for now would be using 
`format: "%Y-%m-%d"`

if that works for you. This is the format that the default should take if it worked correctly.
Thank you!

**Comment by aborruso** [comment]
Thank you

**Comment by aborruso** [comment]
> It is a bug in v.40.8 but fixed in v5 and workaround for now would be using
> `format: "%Y-%m-%d"`

Hi @shashigharti ,
If I run this command using the below schema and [this CSV](https://gist.githubusercontent.com/aborruso/941e9e910d6ab3fb42357cdf417d795a/raw/86bbb2f2452b452b2896857d032096f709f0af15/prezzo_alle_8-20221231.csv)

```
frictionless validate file.yaml --path prezzo_alle_8-20221231.csv
```

I get this error:

```
Type error in the cell "28/12/2022 19:00:07" in row "3" and field "dtComu" at position "5": type is "datetime/%d/%m/%y %H:%M:%S"
```

Why I have it? It seems consistent with the [documentation](https://specs.frictionlessdata.io/table-schema/#types-and-formats).

Thank you


```yaml
# --------
# metadata: prezzo_alle_8-20221001.csv
# --------

name: prezzo_alle_8-20221001
type: table
path: prezzo_alle_8-20221001.csv
scheme: file
format: csv
encoding: utf-8
mediatype: text/csv
dialect:
  headerRows:
    - 2
  csv:
    delimiter: ;
    skipInitialSpace: true
schema:
  fields:
    - name: idImpianto
      type: integer
    - name: descCarburante
      type: string
    - name: prezzo
      type: number
    - name: isSelf
      type: integer
    - name: dtComu
      type: datetime
      format: "%d/%m/%y %H:%M:%S"
```
