### ISSUE TITLE
Validating a tabular JSON file may try to parse arrays as booleans (unhashable type: 'list')

### ISSUE THREAD

**Issue by ronnix** [frictionlessdata/frictionless-py#1293]
Using the latest beta:
```shell
$ frictionless --version
5.0.0b12
```

Let’s say I have a tabular data package with a JSON file where one of the columns has the `array` type:

```yaml
# $ cat testcase1/sample.json
[
    {
        "field": ["aaa", "bbb"]
    },
    {
        "field": []
    }
]
```

```yaml
# $ cat testcase1/datapackage.json
{
  "name": "sample",
  "resources": [
    {
      "path": "sample.json",
      "format": "json",
      "schema": {
        "fields": [
          {
            "name": "foo",
            "type": "array"
          }
        ]
      },
      "profile": "tabular-data-resource"
    }
  ],
  "profile": "tabular-data-package"
}
```

If I try to validate the data, I get this error:
```
$ frictionless validate testcase1

# -------
# invalid: sample.json
# -------

## Summary

+--------------+------------------+
| Name         | Value            |
+==============+==================+
| File Place   | sample.json      |
+--------------+------------------+
| File Size    | (file not found) |
+--------------+------------------+
| Total Time   | 0.016 Seconds    |
+--------------+------------------+
| Rows Checked |                  |
+--------------+------------------+
| Total Errors | 1                |
+--------------+------------------+
| Source Error | 1                |
+--------------+------------------+

## Errors

+-------+---------+--------------+-----------------------------------------------------------------------------------------+
| Row   | Field   | Type         | Message                                                                                 |
+=======+=========+==============+=========================================================================================+
|       |         | source-error | The data source has not supported or has inconsistent contents: unhashable type: 'list' |
+-------+---------+--------------+-----------------------------------------------------------------------------------------+
```

By tracing where the underlying `TypeError` occurs, it looks like the issue happens in `frictionless/fields/boolean.py:value_reader`.

Why would it try to parse the array as a boolean? Well, `Resource.open()` calls `__prepare_schema`, which calls `detect_schema`. Not sure why we would need to detect the schema, as we have an explicit schema to work with... Could we skip that detect part maybe? :thinking:

I can also reproduce a similar error with the following test case:

```yaml
# $ cat testcase2/sample.json
[
    {
        "field": []
    }
]
```

```yaml
# $ cat testcase2/datapackage.json
{
  "name": "sample",
  "resources": [
    {
      "path": "sample.json",
      "format": "json",
      "schema": {
        "fields": [
          {
            "name": "foo",
            "type": "boolean"
          }
        ]
      },
      "profile": "tabular-data-resource"
    }
  ],
  "profile": "tabular-data-package"
}
```

```shell
$ frictionless validate testcase2
unhashable type: 'list'
```
