### ISSUE TITLE
Relational and conditional constraints

### ISSUE THREAD

**Issue by damianooldoni** [frictionlessdata/frictionless-py#1345]
I really enjoy using frictionless to validate my data (resource) based on a table schema. 
I like the simplicity of describing the fields type and its constraints. However, the constraints I found in the documentation are sometimes not enough.

Is there a way to implement relational and conditional constraints?
Example: you have two columns, `startDate` and `endDate`. You want to check your data satisfy a.o. this constraint:
(`endDate >= startDate`) or (`endDate  == startDate == NULL`). How to write it in a table.schema?

Thanks in advance!

**Comment by roll** [comment]
Hi @damianooldoni, 

There is a Row Constraint - https://framework.frictionlessdata.io/docs/checks/row.html#row-constraint (it's not a part of the standards and works only with Frictionless Framework)

You can have a resource looking like this:

```yaml
path: table.csv
schema: <schema>
checklist:
  checks:
    - type: row-constraint
      formula: field1 > field2
```
