### ISSUE TITLE
Custom plugins with pipeline.from_descriptor() do not work

### ISSUE THREAD

**Issue by ghost** [frictionlessdata/frictionless-py#1357]
When custom steps are initialized as plugins through PYTHONPATH, they are arbitrarily added to pipelines and cannot be utilized.

For instance, when we have the following pipeline, with the custom step `cell-array-join` and we create a Pipeline from this configuration. The pipeline steps are incorrectly configured from Pipeline.from_descriptor().

Pipeline:
```
steps:
 - type: resource-transform
  name: main
  steps:
   - type: cell-set
    fieldName: Date Generated
    value: Zeroed
   - type: cell-array-join
    fieldName: Entity Type
```

Pipeline Steps:
```{'steps': [{'type': 'cell-array-join',
      'name': 'main',
      'steps': [{'type': 'cell-set',
            'fieldName': 'Date Generated',
            'value': 'Zeroed'},
           {'type': 'cell-array-join',
            'fieldName': 'Entity Type'}]}]}
```
