### ISSUE TITLE
A valid CSV mapped as not valid?

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1384]
Hi,
I have [this CSV](https://gist.githubusercontent.com/aborruso/9fecbec0e38f2956d9cc17659e8bb964/raw/ff158d35b36f6b97db2c813870bdd4cb7e9eb8ae/input.csv), that seems to me valid.

But if I run validate on it, I have a lot of errors.

Am I wrong or frictionless cli?

Thank you

**Comment by roll** [comment]
Hi @aborruso,

It seems Python's csv sniffer can't detect delimiter correctly. It works if we provide it explicitly:

```
frictionless describe tmp/issue-1384.csv --dialect '{"csv": {"delimiter": ";"}}'
```
```
schema:
  fields:
    - name: Codice univoco programma
      type: string
    - name: Programma
      type: string
    - name: Descrizione programma
      type: string
```
