### ISSUE TITLE
Review/improve Catalog implementation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1439]
# Overview

Currently, the catalog is designed copying the package/schema structure:

```
packages:
  - dp1.json
  - dp2.json
```

We might consider reworking it to provide more metadata for every package:

```
datasets:
  - name: name1
    package: dp1.json
    ...
  - name: name2
    package: dp2.json
    ...
```

The reason behind this is that usually `datapackage.json` is already a published container and might be remote so it will not be possible to alter package names and provide additional metadata.
