### ISSUE TITLE
Extracting data from a CSV, using a description file

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1605]
Hi all,
once a year I ask almost the same question, and I feel kind of dumb :(

I have this **yml** schema: https://gist.githubusercontent.com/aborruso/fc64cbf1abd22ca43029ed35f577ac07/raw/ed025c80bfe78411915c90abca65227a1aa24b19/check.yml

And this is my **source CSV file** https://gist.githubusercontent.com/aborruso/60ea53f471409f7d0fcfd911ef9a9510/raw/88b18b8b22216530aa456ab411c39efbc285ab5c/input.csv

I need to use the yml, to extract valid records, from a lot of similar CSV files.

In an old script I used this command and it worked:

```
frictionless extract --valid check.yml --path input.csv
```

Now I have this error:

```
[error] Resource with data type "file" is not extractable
```

What's wrong in my command? How to use the yml file to extract valid values from my csv files?

I'm using 5.15.5 version.

Thank you

**Comment by roll** [comment]
Hi @aborruso,

Sorry for the long investigation. I think it's kind of edge to the way `fricitonless-py` is used but I made it work updating the description (note yml -> yaml):

> check.yaml

```yaml
encoding: iso8859-1
name: provincia
path: <replace-me> # added and `scheme` is removed
profile: tabular-data-resource
format: csv
hashing: md5
...
```

```bash
frictionless extract --type resource tmp/issue1605.yaml --path https://gist.githubusercontent.com/aborruso/60ea53f471409f7d0fcfd911ef9a9510/raw/88b18b8b22216530aa456ab411c39efbc285ab5c/input.csv --valid
```

**Comment by aborruso** [comment]
Thank you @roll.

I would not add path, because with the same yaml (a sort of template) I would like to check file_a, file_3 ecc.
Could I add an hardcoded path and then run `frictionless extract --valid check.yml --path lorem_ipsum.csv`?

Moreover I have editer my yaml, now it is in this way:
https://gist.github.com/aborruso/9a6b181f7587a6d717810f332562d49b

If I run

```
frictionless extract --type resource check.yml --path https://gist.githubusercontent.com/aborruso/60ea53f471409f7d0fcfd911ef9a9510/raw/88b18b8b22216530aa456ab411c39efbc285ab5c/input.csv --valid
```

I get 

```
[resource-error] The data resource has an error: cannot retrieve metadata "check.yml" because "Expecting value: line 1 column 1 (char  │
│ 0)
```

Thank you

**Comment by roll** [comment]
@aborruso 
Sorry, I wasn't clear `path: <replace-me>` is basically a dummy path that needs to be present to make a descriptor valid but intended to be replaced in a CLI command with `--path`.

In general, I would think more of kind of command like this:

```
frictionless extract table.csv --encoding utf-8 --dialect dialect.json --schema schema.json
```

Little bit more verbose but semantics is cleaner in my opinion

**Comment by aborruso** [comment]
> Sorry, I wasn't clear `path: <replace-me>` is basically a dummy path that needs to be present to make a descriptor valid but intended to be replaced in a CLI command with `--path`.

Thank you @roll now I have

```
encoding: iso8859-1
name: provincia
profile: tabular-data-resource
format: csv
path: dummy.csv
hashing: md5
```

If I run `frictionless extract --type resource check.yml --path input.csv`, I have 

```
[resource-error] The data resource has an error: cannot retrieve metadata "check.yml" because "Expecting value: line 1 column 1 (char │ │ 0)"
```

The same if I run

```
frictionless extract input.csv --schema check.yml
```


I'm using 5.16.0

Thank you

**Comment by roll** [comment]
@aborruso 
Can you please try `check.yaml` with `yaml` extension? If it doesn't work I will need some time for additional investigation

**Comment by aborruso** [comment]
> Can you please try `check.yaml` with `yaml` extension? If it doesn't work I will need some time for additional investigation

There is something I do not understand: does it work for you?

I have renamed it to `check.yaml`. If I run `frictionless extract input.csv --schema check.yaml`, I have

```
[schema-error] Schema is not valid: descriptor is not valid (Schema is not valid: 'fields' is a required property)
```

My files [check.zip](https://github.com/frictionlessdata/frictionless-py/files/13487215/check.zip)

Thank you

**Comment by roll** [comment]
Hi @aborruso,

Yes with your `check.zip` extracted (we use type to hint what kind of input we use -- a resource descriptor):

```
frictionless --version
# 5.16.0
frictionless extract --type resource check.yaml --path input.csv
# expected output
```

What I meant by using schema/dialect is reworking the workflow like this:

```
frictionless extract input.csv --encoding utf-8 --dialect dialect.yaml --schema schema.yaml
```

Where

> dialect.yaml

```yaml
delimiter: ;
skipInitialSpace: true
headerRows:
  - 3
```

> schema.yaml

```yaml
missingValues:
  - ""
fields:
  - type: string
    name: codice_regione
    description: "Il codice regione secondo la classificazione ISTAT ...."
    constraints:
      required: true
      pattern: ^[0-9]{2}$
  - type: string
    name: codice_provincia
    constraints:
      required: true
      pattern: ^[0-9]{3}$
  - type: string
    name: codice_comune
    constraints:
      required: true
      pattern: ^[0-9]{4}$
  - type: string
    name: denominazione_comune
    constraints:
      required: true
  - type: string
    name: sigla_provincia
    constraints:
      required: true
  - type: integer
    name: popolazione_censita
    constraints:
      required: true
  - type: string
    name: titolo_accademico
  - type: string
    name: cognome
    constraints:
      required: true
  - type: string
    name: nome
    constraints:
      required: true
  - type: string
    name: sesso
    description: "Solo due valori ammmessi. M = Maschio, F = Femmina"
    constraints:
      enum:
        - M
        - F
  - type: date
    name: data_nascita
    description: "La data di nascita in formato giorno/mese/anno"
    format: "%d/%m/%Y"
    example: "22/01/1970"
  - type: string
    name: luogo_nascita
  - type: string
    name: descrizione_carica
    constraints:
      required: true
  - type: date
    name: data_elezione
    format: "%d/%m/%Y"
    constraints:
      required: true
  - type: date
    name: data_entrata_in_carica
    format: "%d/%m/%Y"
    constraints:
      required: true
  - type: string
    name: partito
  - type: string
    name: titolo_studio
  - type: string
    name: professione
```

In this case we use two standards Table Schema and Table Dialect (coming in specs v2) instead of patching a resource descriptor that is supported in `frictionless-py` but it's only on the software level in Python, and more like an "aside feature" as Data Resource doesn't really meant to be used with different paths as it's a "bound descriptor" compared to "abstract descriptor" schema/dialect. Of course, it needs to be better document but I hope we're getting there esp. with this spec v2 work
