### ISSUE TITLE
Sheet selection does not work for Open Document files (ods)

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1702]
# Overview

The selection of sheets does not work for Open Document files (ods). The first sheet is always used. However, it works for Excel files.

## How to reproduce

```shell
frictionless describe --yaml --sheet TableB multi.ods
```

results in

```yaml
name: multi
type: table
path: multi.ods
scheme: file
format: ods
mediatype: application/vnd.oasis.opendocument.spreadsheet
encoding: utf-8
dialect:
  excel:
    sheet: TableB
schema:
  fields:
    - name: a
      type: integer
    - name: b
      type: integer
    - name: c
      type: integer
```

However, the second sheet contains different information. This happens when you do the same with the Excel file:

```shell
frictionless describe --yaml --sheet TableB multi.xlsx
```

results in

```yaml
name: multi
type: table
path: multi.xlsx
scheme: file
format: xlsx
mediatype: application/vnd.ms-excel
encoding: utf-8
dialect:
  excel:
    sheet: TableB
schema:
  fields:
    - name: x
      type: integer
    - name: y
      type: integer
    - name: z
      type: integer
```

Version: 5.18.0

[multi.ods](https://github.com/user-attachments/files/17617345/multi.ods)
[multi.xlsx](https://github.com/user-attachments/files/17617349/multi.xlsx)
