### ISSUE TITLE
Add number of fields to describe output

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#440]
# Overview

In the output we have `rows: 4`. I think it would be great to have also `fields: numberOfFields`.

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks,

do you mean to the `validate` output like `tables[].stats.rows`?

**Comment by aborruso** [comment]
@roll thank you to you for this really great tool.

I mean that, starting in example from

```
field_1,field_2,field_3
2008,a,148
2008,b,26
2009,b,38
2019,c,7
```

and running describe `frictionless describe input.csv`, I should have also the number of fields in the output.
Below an example (`fields: 3`)

```
[metadata] tmp.csv

bytes: 64
compression: 'no'
compressionPath: ''
dialect: {}
encoding: utf-8
format: csv
hash: c7a3eb65f5e415b9a76f55c754f8356b
hashing: md5
name: tmp
path: tmp.csv
profile: tabular-data-resource
rows: 4
fields: 3
schema:
  fields:
    - name: field_1
      type: integer
    - name: field_2
      type: string
    - name: field_3
      type: integer
scheme: file
```
