### ISSUE TITLE
Fix error message on yml extension or support it

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#644]
Hi,
I'm reading https://framework.frictionlessdata.io/docs/guides/getting-started/#usage manual, but I didn't understand what the basic workflow to follow, using the gli.

Imagine I have this CSV:

```
string,number,date
one,1,2021-01-01
two,2,2021-01-02
```

If I run `frictionless describe tmp.csv`, I have

```
---
metadata: tmp.csv
---

encoding: utf-8
format: csv
hashing: md5
name: tmp
path: tmp.csv
profile: tabular-data-resource
schema:
  fields:
    - name: string
      type: string
    - name: number
      type: integer
    - name: date
      type: date
scheme: file
stats:
  bytes: 53
  fields: 3
  hash: 764797fe75bece2a3175303181b48912
  rows: 2
```

If I want to create a Frictionless CSV using the cli, what's the steps do I must run?

Is the one to save the describe output, running `frictionless describe tmp.csv >tmp.resource.yml`?

Once I have it, if I run `frictionless validate tmp.resource.yml --basepath .` I have 

```
---
invalid: tmp.resource.yml
---
==========  ========================================================
code        message
==========  ========================================================
task-error  The task has an error: 'NoneType' object is not iterable
==========  ========================================================
```

Seeing the error I think I have not understood anything and I stop. Then what are the steps i should take to build my first hello world frictionless CSV, using the cli? 

Thank you

**Comment by roll** [comment]
Hi @aborruso, It's:

```
frictionless describe tmp.csv >tmp.resource.yaml # YAML no YML
frictionless validate tmp.resource.yaml --basepath .
```

But thanks for the feedback as this error message definitely needs to be improved (or we need to allow yml extension also)

**Comment by aborruso** [comment]
Hi @roll first of all thank you for your work. This new version seems bombastic.

I have this CSV

```
id,colore,nomeTesto,NUTS_code,NUTS_level
abruzzo,giallo,Abruzzo,ITF1,2
basilicata,giallo,Basilicata,ITF5,2
calabria,giallo,Calabria,ITF6,2
```

If I run `frictionless describe tmp.csv >tmp.resource.yaml` I have

```yaml
---
metadata: tmp.csv
---

encoding: utf-8
format: csv
hashing: md5
name: tmp
path: tmp.csv
profile: tabular-data-resource
schema:
  fields:
    - name: id
      type: string
    - name: colore
      type: string
    - name: nomeTesto
      type: string
    - name: NUTS_code
      type: string
    - name: NUTS_level
      type: integer
scheme: file
stats:
  bytes: 775
  fields: 5
  hash: 8939597dcbed41b17b3a59ed2585c52d
  rows: 21
```

Also using `yaml` I have error. If I run `frictionless validate tmp.resource.yaml --basepath .` I have

```
---
invalid: tmp.resource.yaml
---
==============  =========================================================================================================================================================================================================================
code            message                                                                                                                                                                                                                  
==============  =========================================================================================================================================================================================================================
resource-error  The data resource has an error: cannot extract metadata "tmp.resource.yaml" because "expected a single document in the stream
  in "<file>", line 2, column 1
but found another document
  in "<file>", line 3, column 1"
==============  =========================================================================================================================================================================================================================
```

It seems I must delete the below strings from the yaml. Is this the cli pipeline?

```
---
metadata: tmp.csv
---
```

**Comment by roll** [comment]
Sorry @aborruso,

We need to provide an output format:

```
frictionless describe tmp.csv --yaml > tmp.resource.yaml
frictionless describe tmp.csv --json > tmp.resource.json
```

Also you don't need a basepath if you save metadata to the current dir:

```
frictionless validation tmp.resource.yaml
```

**Comment by aborruso** [comment]
Thank you. I felt completely stupid, while I am only partially :)

Ok, I hope to be able to build a complete frictionless cli pipeline as soon as poosible. If I will write something useful, I share it with you. It could be useful for current documentation.

**Comment by aborruso** [comment]
Thank you very much

**Comment by aborruso** [comment]
@roll I have a strange and probably really stupid problem

My input is

```
fieldA,fieldB
a,1
b,2
```

I run `frictionless describe input.csv --yaml >input.schema.yaml` and I have

```yaml
encoding: utf-8
format: csv
hashing: md5
name: input
path: input.csv
profile: tabular-data-resource
schema:
  fields:
    - name: fieldA
      type: string
    - name: fieldB
      type: integer
scheme: file
```

If I validate it, running `frictionless validate input.schema.yaml`, I have

```
# -------
# invalid: input.schema.yaml
# -------
============  =====================================================================================================
code          message
============  =====================================================================================================
schema-error  Schema is not valid: "'fields' is a required property" at "" in metadata and at "required" in profile
============  =====================================================================================================
```

What's my stupid error?
