### ISSUE TITLE
frictionless transform returns success even when the source file does not exist

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#814]
# Overview

Hi,
I have the below transform file, and the source file does not exist.

If I run `frictionless transform trasform.yaml` I have

```
# -------
# success: transform.yaml
# -------
```

Thank you

```
tasks:
  - type: resource
    source: blablabla.csv
    steps:
      - code: cell-replace
        fieldName: neighbor_id
        pattern: '22'
        replace: '2'
      - code: cell-replace
        fieldName: population
        pattern: 'n/a'
        replace: '67'
      - code: row-filter
        formula: population
      - code: field-update
        name: neighbor_id
        type: integer
      - code: table-normalize
      - code: table-write
        path: ../../../output/countries.csv
```

---

Please preserve this line to notify @roll (lead of this repository)
