### ISSUE TITLE
Feature request: number of records constraints

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#820]
# Overview

Hi,
below you have one of the official documentation yaml file. There some constraints fields related.

A lot of time I know that I know that a resource is valid only if it is made up of at least 365 rows (some annual dataset including leap years). Or that the rows shouldn't be more than 10.

I think it should be a great validate and check feature to have.

Thank you

```
dialect:
  delimiter: ;
encoding: utf-8
format: csv
hashing: md5
layout:
  headerRows:
    - 2
name: country-2
path: country-2.csv
profile: tabular-data-resource
schema:
  fields:
    - name: id
      title: Identifier
      type: integer
    - name: neighbor_id
      title: Identifier of the neighbor
      type: integer
    - name: name
      title: Name of the country
      type: string
    - constraints:
        minimum: 0
      description: According to the year 2020's data
      name: population
      title: Population
      type: integer
  foreignKeys:
    - fields:
        - neighbor_id
      reference:
        fields:
          - id
        resource: ''
scheme: file
```

---

Please preserve this line to notify @roll (lead of this repository)
