### ISSUE TITLE
How to validate a file, using a schema created for another one?

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#834]
# Overview

Hi,
I have this start CSV file:

```
denominazione_comune,lat,long
Catenanuova,37.570890,14.693100
Beldi,3.570890,13.693100
```

Starting from it,  have created this yaml description:

```yaml
encoding: utf-8
format: csv
hashing: md5
name: tmp
path: tmp.csv
profile: tabular-data-resource
schema:
  fields:
    - name: denominazione_comune
      type: string
    - name: lat
      type: number
    - name: long
      type: number
scheme: file
```

I have also this second CSV file:

```
fieldA,fieldB
a,3
b,4
```

I wold like to use the above yaml file to  validate this second (wrong) CSV file, both for the fields and for encoding, format, ecc.. Is it possible to do it? Os is it possible "only" to validate the schema ([in this way](https://github.com/frictionlessdata/project/discussions/637#discussioncomment-567155))? 

Thank you

---

Please preserve this line to notify @roll (lead of this repository)
