### ISSUE TITLE
frictionless cli does not read accented characters 

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#844]
# Overview

Hi,
in Italian, my language, we use a lot of accented characters .
"age" in example is "età".

If I have this input file

```
nome,età
andy,47
tom,67
```  

and run extract I have

```
# ----
# data: im.csv
# ----

====  ===
nome  etÃ
====  ===
andy   47
tom    67
====  ===
```

If I run describe I have

```
encoding: iso8859-9
format: csv
hashing: md5
name: im
path: im.csv
profile: tabular-data-resource
schema:
  fields:
    - name: nome
      type: string
    - name: "et\xC3"
      type: integer
scheme: file
```

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by aborruso** [comment]
@roll now I have 4.10.3 and I have the same error

```
frictionless extract https://gist.githubusercontent.com/aborruso/da7e09e6f17d3f0c7fa806d56111db78/raw/049080378a9c60dbd9098507c473cfa572863eb2/input.csv
```

I have  `etÃ` and not `età`:

```
# ----
# data: https://gist.githubusercontent.com/aborruso/da7e09e6f17d3f0c7fa806d56111db78/raw/049080378a9c60dbd9098507c473cfa572863eb2/input.csv
# ----

====  ===
nome  etÃ
====  ===
andy   47
tom    67

====  ===
```

**Comment by roll** [comment]
@aborruso 
Yea I had the same as `chardet` detect encoding as `iso8859-9`. 

It works fine if we set `utf-8`:

```bash
$ frictionless describe data/issue-844.csv --encoding utf-8
```
```yaml
# --------
# metadata: data/issue-844.csv
# --------

encoding: utf-8
format: csv
hashing: md5
name: issue-844
path: data/issue-844.csv
profile: tabular-data-resource
schema:
  fields:
    - name: nome
      type: string
    - name: età
      type: integer
scheme: file
```
