### ISSUE TITLE
Usage of 'trusted' unsafe paths?

### ISSUE THREAD

**Issue by ewheeler** [frictionlessdata/frictionless-py#856]
# Overview

While running through the [python basic examples](https://framework.frictionlessdata.io/docs/guides/basic-examples) on my machine, I substituted `/tmp/example.csv` instead of the `countries.csv` filename used in the example.

Following the example I get a `/tmp/example.resource.yaml` file that contains:

```
encoding: utf-8
format: csv
hashing: md5
layout:
  headerRows:
    - 3
name: example
path: /tmp/example.csv
profile: tabular-data-resource
schema:
  fields:
    - name: id
      type: integer
    - name: neighbor_id
      type: integer
    - name: name
      type: string
    - name: population
      type: integer
  foreignKeys:
    - fields:
        - neighbor_id
      reference:
        fields:
          - id
        resource: ''
  missingValues:
    - ''
    - n/a
scheme: file
```

All works well except for this bit:
```
rows = extract('/tmp/example.resource.yaml')
pprint(rows)
```

which raises `FrictionlessException: [resource-error] The data resource has an error: path "['/tmp/example.csv']" is not safe`

I noticed that [Resource](https://framework.frictionlessdata.io/docs/references/api-reference#resource) and [Package](https://framework.frictionlessdata.io/docs/references/api-reference#package) have `trusted` flags, but including `trusted=True` as a parameter to `extract` raises `FrictionlessException: [scheme-error] The data source could not be successfully loaded: [Errno 2] No such file or directory: '/tmp//tmp/example.csv'`

I also tried to pass an explicitly-trusted `Resource` object to `extract` like:
```
resource = Resource('/tmp/example.resource.yaml', trusted=True)
rows = extract(resource)
pprint(rows)
```
but get the same `No such file or directory` exception.

I understand that using absolute paths is strongly discouraged per the [spec's warning](https://specs.frictionlessdata.io/data-resource/#data-location), but since the `trusted` flags exist I figured it might be possible. I'm not sure if this is the expected behavior or user error on my part. Appreciate any pointers!
