### ISSUE TITLE
Consider a mode when a schema can shape output data

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#922]
# Overview

Currently, we have:
- default mode when schema fields should follow table columns to work
- a `schema_sync` mode when schema can have less columns or in different order to by synced with data

It would be great to have also a mode when the schema defines the output data. Especially it's relevant for the Hansdontable integration in Livemark:

```yaml
data:
  path: data/table.csv
  # I want to shape data output here both columns and their order
  schema:
    type: define # or other flag
    fields:
      - name: field100
        type: number
      - name: field1
        label: some # ability to pick a column by a header's label
        type: date
filters: true
dropdownMenu: true
columnSorting:
  initialConfig:
    column: 1
    sortOrder: desc
```

Other suggestions:

---

Initial thread - https://github.com/frictionlessdata/specs/issues/704#issuecomment-733171792

---

Probably we need another argument to achieve the behavior mentioned above but the requirements should be analyzed first.

---

https://github.com/frictionlessdata/project/discussions/636#discussioncomment-1341223
